name: app_linkster
description: AppLinkster simplifies the process of opening specific apps using tailored deep links.
version: 0.0.5
homepage: https://beingthere.dev
repository: https://github.com/mohn93/app_linkster

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  logger: ^2.0.2+1
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2


flutter:
